name: 'ECS Scale Up'
description: 'Scale up ECS Service count and deploy a task definition'
inputs:
  aws-access-key-id:
    description: >-
      AWS Access Key ID. This input is required if running in the GitHub hosted environment.
      It is optional if running in a self-hosted environment that already has AWS credentials,
      for example on an EC2 instance.
    required: false
  aws-secret-access-key:
    description: >-
      AWS Secret Access Key. This input is required if running in the GitHub hosted environment.
      It is optional if running in a self-hosted environment that already has AWS credentials,
      for example on an EC2 instance.
    required: false
  aws-region:
    description: 'Your AWS region'
    required: true
    default: 'us-east-1'
  ecr-repository:
    description: 'The ECR repository housing the image you want to use.'
    required: true
  image-tag:
    description: 'The unique tag of a specific image to pull from your ECR repository.'
    required: false
    default: 'latest'
  container-name:
    description: 'The container name listed in the task definition you will deploy.'
    required: true
  task-definition:
    description: 'The task definition family name.'
    required: true
  service:
    description: 'The name of the ECS service.'
    required: true
  cluster:
    description: 'The name of the ECS cluster the service belongs to.'
    required: true
  desired-count:
    description: 'The number of ECS tasks you wish to deploy.'
    required: true
    default: '1'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'